[2023-09-20T16:09:47.890+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test-dag.get_update_date scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-09-20T16:09:47.893+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test-dag.get_update_date scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-09-20T16:09:47.893+0900] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T16:09:47.901+0900] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): get_update_date> on 2023-01-01 00:00:00+00:00
[2023-09-20T16:09:47.902+0900] {standard_task_runner.py:57} INFO - Started process 30443 to run task
[2023-09-20T16:09:47.904+0900] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'test-dag', 'get_update_date', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmppcwjbtol']
[2023-09-20T16:09:47.904+0900] {standard_task_runner.py:85} INFO - Job 7: Subtask get_update_date
[2023-09-20T16:09:47.931+0900] {task_command.py:415} INFO - Running <TaskInstance: test-dag.get_update_date scheduled__2023-01-01T00:00:00+00:00 [running]> on host DESKTOP-FF35UUU.
[2023-09-20T16:09:47.964+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test-dag' AIRFLOW_CTX_TASK_ID='get_update_date' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2023-09-20T16:09:47.965+0900] {sql.py:274} INFO - Executing: SELECT * FROM engine_task WHERE update_date BETWEEN %(begin_date)s AND %(end_date)s
[2023-09-20T16:09:47.968+0900] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-09-20T16:09:48.022+0900] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-09-20T16:09:49.114+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/sjpark/anaconda3/envs/airflow_env/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known

[2023-09-20T16:09:49.122+0900] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=test-dag, task_id=get_update_date, execution_date=20230101T000000, start_date=20230920T070947, end_date=20230920T070949
[2023-09-20T16:09:49.130+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task get_update_date (could not translate host name "postgres" to address: Name or service not known
; 30443)
[2023-09-20T16:09:49.161+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T16:09:49.168+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
